services:
  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: strong-password
      MYSQL_USER: sdpx
      MYSQL_PASSWORD: sdpx
      MYSQL_DATABASE: sdpx  
    volumes:
      - mydb:/var/lib/mysql
    ports:
      - 3306:3306
      
volumes:
  mydb:
